name: Java CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile
        run: javac src/main/java/org/example/HelloWorld.java

      - name: Run
        run: java -cp src/main/java org.example.HelloWorld
